### ISSUE TITLE
Liên hệ

### ISSUE THREAD

**Issue by JinJin1503** [JinJin1503/Khanh_Di#36]
Cung cấp phương tiện để khách hàng gửi câu hỏi, phản hồi hoặc yêu cầu hỗ trợ

**Comment by Sinnerjudging** [comment]
[Contact.zip](https://github.com/user-attachments/files/17742600/Contact.zip)

**Comment by YenDi05** [comment]
[Contact.zip](https://github.com/user-attachments/files/17852668/Contact.zip)
