### ISSUE TITLE
Tài liệu đặc tả Project

### ISSUE THREAD

**Issue by YenDi05** [JinJin1503/Khanh_Di#54]

**Comment by YenDi05** [comment]
[data.docx](https://github.com/user-attachments/files/17849466/data.docx)

**Comment by YenDi05** [comment]
[KoiFarmShop.docx](https://github.com/user-attachments/files/17853958/KoiFarmShop.docx)

**Comment by YenDi05** [comment]
[use-case.docx](https://github.com/user-attachments/files/17853964/use-case.docx)

**Comment by JinJin1503** [comment]
[diagram.docx](https://github.com/user-attachments/files/17853995/diagram.docx)
